### ISSUE TITLE
Add categories to your links

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-dump#1]
We should allow users to add a little note to their links

**Comment by torch2424** [comment]
This feature is still on the fence. It will increse our backend size, and may not fit the philosophy of the app

**Comment by torch2424** [comment]
Moving to public beta, this gon take a while

**Comment by julianpoy** [comment]
This is now my main focus. I am working on this, then progressing to #26.

**Comment by torch2424** [comment]
Yesss <3
