### ISSUE TITLE
Forgot Password - $mdToast is not defined

### ISSUE THREAD

**Issue by julianpoy** [torch2424/link-dump#101]
Currently, if you try to use "Forgot Password", the page breaks with a console error "$mdToast is not defined"

**Comment by julianpoy** [comment]
This is actually kind of important. Forgot password is rather essential. Could you handle this, since I am inexperienced with your mdtoast stuff?

**Comment by torch2424** [comment]
Oh yeah, i'll do it in about an hour
 :D

**Comment by torch2424** [comment]
And also, dont be afraid of mdToast, I made it SUPERRRRR easy.

I made a service called toasty.

So in ject "Toasty"

and call Toasty.show(Text, timeout(default is 3000 milliseconds));

I am doing this, justwanted to share the knowledge :)

**Comment by julianpoy** [comment]
Excellent. Thanks for the tips. I was scared because I had no idea that you wrote it up.
