### ISSUE TITLE
Card width too long on non-title scraped links

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-dump#102]
Since the title scraper HTTPS is acting up, our links aren't being title scraped, forcing them to extend our cards farther than the max width.

This can be fixed with a predefined wordwrap and width CSS on the link text.

Issue provided by Alexis :)

**Comment by julianpoy** [comment]
This is important even though title-scraping has been fixed. There are actually title-scraped titles that are too long for the current card format.

**Comment by torch2424** [comment]
Yeah this is a css bug.

To be completly honest, I gotta take some time to work on my android apps however. My code is terrible. Like really bad, and I have a lot of users that I've been neglecting. So android finally allows for promo codes, so I'll probably shoot promo codes to my paid apps for anyone who asked for my help, and then tell them to check out for the update :)

**Comment by torch2424** [comment]
the fix in backToColumns. And should be in master actually...

**Comment by torch2424** [comment]
This was already fixed in master, just never pushed to live. closing...
