### ISSUE TITLE
Do Research on UX/UI And some more styling

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-dump#11]
We should do some more styling and research on UX and UI for linkDump

**Comment by julianpoy** [comment]
+1
Perhaps examine the applications odd (extreme) similarity to Google Keep and make changes accordingly...

**Comment by torch2424** [comment]
Hahaha I love google keep. It's interface is nice :') Google recently released a course on material design on udacity :)

**Comment by julianpoy** [comment]
I know, I love it too. Perhaps we should develop our own design and feel though... Especially since our functionality is quite similar to Google Keep.

**Comment by torch2424** [comment]
as mention in #15 

Might I suggest you try 
http://css3buttongenerator.com/ OR
http://www.skyafar.com/bootstrap/flat-button-generator/
for the find button? Might make it a little easier to click.

for the find button

**Comment by torch2424** [comment]
@julianpoy alright I'm down for that design jazz. And our functionality is like da bomp. Kinda like google keep, but I think it goes down a different branch though!

**Comment by torch2424** [comment]
After researching and finding some good resources,

I decided to stick with materializecss, its beautiful, and really does have a good design perspective towards apps.

I looked through all of the frameworks listed here: https://www.reddit.com/r/css/comments/2uhr7o/what_kind_of_css_framework_cool_kids_use_these/

But they just mostly focused on grid systems, and didnt provide much of a feel.

**Comment by torch2424** [comment]
Finished from c72273a59cebb0d940cec05ff6c9bff2d06d70ae

**Comment by torch2424** [comment]
And looks amazing :')

![screenshot from 2015-09-04 20 36 08](https://cloud.githubusercontent.com/assets/1448289/9697497/9ec472f6-5344-11e5-9f30-da0abb0d1471.png)
