### ISSUE TITLE
Add sorting to the link card

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-dump#15]
the main link card should have a search bar for sorting. this should be implemented

**Comment by torch2424** [comment]
Doing this now

**Comment by torch2424** [comment]
Looking good as of 14fdefe39adc5fdd56280aa660f5ab2576273ff8

However, this is still slow, possibly @julianpoy can help with this?

![untitled recording](https://cloud.githubusercontent.com/assets/1448289/9642574/ba4fb8a2-5171-11e5-8f67-d35ea4232ff5.gif)

**Comment by julianpoy** [comment]
Yup. Working on this now.

**Comment by torch2424** [comment]
@julianpoy I love you

**Comment by julianpoy** [comment]
Might I suggest you try 
http://css3buttongenerator.com/ OR
http://www.skyafar.com/bootstrap/flat-button-generator/
for the find button? Might make it a little easier to click.

**Comment by torch2424** [comment]
I think its from the iframes reloading, maybe #7 will help solve this? I know a good npm package for this. And also, have you seen my buisiness model? https://github.com/torch2424/link-dump/wiki/Business-Model

And also, I shall creat ean issue for a button I agree its hard to see, but I didnt want it to be like the BAM when you enter the page

**Comment by julianpoy** [comment]
I agree thats part of the problem, however angular's "filter" is very slow from the start.
Read the "limit dom filters" part of this article. I think you should look into doing that.
https://www.binpress.com/tutorial/speeding-up-angular-js-with-simple-optimizations/135

**Comment by torch2424** [comment]
Can also sort by titles now. As they are now added the the dump object upon response

via f5701452852b6112af471023dec84c04332966a2

simply need to add js filter and then done!

**Comment by torch2424** [comment]
Julian, your article was good, and made some good points, but look at this ;)

http://php.quicoto.com/use-ng-show-filtering-data-angularjs/

I used this, and my god does this stiff work beautiful. it runs like a cheetah on cocaine now ;)

**Comment by torch2424** [comment]
Finished via 96ac6790137d4b9fc60d7cdb0ea0246af630ab58
