### ISSUE TITLE
Fill out the my Account page

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-dump#2]
We should allow users to change their password, and possibly even their username

**Comment by julianpoy** [comment]
This should probably be done before release. Should we be creating some milestones?

**Comment by torch2424** [comment]
Naw not yet, well I didnt even plan to release right right now, just have it up, so we could use it for our personal lives haha!

**Comment by julianpoy** [comment]
Ill do this, because it has to do with a lot of unimplemented functionality in the backend.

**Comment by torch2424** [comment]
Alright cool! THanks dude!

**Comment by torch2424** [comment]
@julianpoy is it alright If I make the frontend for this? I notcied alot of remainig issues are backend things. And I'd like to work on this some more!

**Comment by julianpoy** [comment]
I haven't been programming for the last few days. I am picking up development again. Ill handle this because it has so much backend related.
Perhaps you could work on the cards and other frontend bugs that are happening. There are a lot. Look at the v0.2 milestone.

**Comment by torch2424** [comment]
yee I am
