### ISSUE TITLE
Work a little bit more on Responsiveness

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-dump#21]
Everything scales beautfully on mobile.

However, bandcamp iframes break the card panels.

Video iframes are not responsize, and are very tall, but not much width for the thumbnail.

Performance is MUCH MUCH MUCH MUCH MUCH better than I had anticipated, and the lazy loading does a ton of help. but it could always be a little bit better.

**Comment by julianpoy** [comment]
I agree, and I think it would be nice to see this as soon as possible. In addition, I notice that when using two-column view, the links aren't sorted horizontally by date. They go vertically first, to the bottom. This means that the top two are the newest link and a link from exactly the middle of your link-dump history.
Although it does bring attention to old links, I don't think its a feature.

**Comment by torch2424** [comment]
Oh yeah that definitely isnt, I'll look into that!
