### ISSUE TITLE
Cool Favicon

### ISSUE THREAD

**Issue by julianpoy** [torch2424/link-dump#27]
We need an awesome favicon! Perhaps a link?
Its hard to track down what tab is which in my mess of tabs when a website doesn't have a unique favicon. To help my poor soul, and to make the app better, I suggest a favicon!

**Comment by torch2424** [comment]
Ayyyyeeeeee I'm down for that jazz! :D

**Comment by julianpoy** [comment]
Just an FYI, this is as simple as creating an favicon.ico on a free internet favicon creator in HD, and putting it in the root of our server.

**Comment by torch2424** [comment]
Yeah I got it, I'm gonna make it in like some fun shape maker thingy
