### ISSUE TITLE
Easier Readability

### ISSUE THREAD

**Issue by julianpoy** [torch2424/link-dump#28]
We should make the link titles bigger, so that it is easier to read them. Perhaps make them be a better flat font as well?
I have a hard time looking through a bunch of standard links and finding what I need.

**Comment by torch2424** [comment]
I got chu ;)

**Comment by julianpoy** [comment]
I will handle this. I did a quick design of it and it seems pretty good.
https://www.dropbox.com/s/w3rvlii5mlsd4nz/Screenshot%202015-09-13%2020.07.12.png?dl=0

**Comment by torch2424** [comment]
But the nice blue background :o

And this doesnt have much color to it. To be honest, I feel like that design is very bland. How about we just have like a readability setting or something? So people can choose to use that design to do that

**Comment by julianpoy** [comment]
I showed it to alexis, and she agrees that it is easier to read it without the blue. The blue is very hard on the eyes, and makes it hard to read anything on the page. Thats usually why webpages have white backgrounds in the first place.
If you look carefully at the design I posted, you will see its actually a pretty texture in the background. It is bland on purpose. The original issue came up because the page was too not-bland, and therefore made it hard to read what was important in the app.

**Comment by torch2424** [comment]
@julianpoy I showed it to daniel to compare, and he wasnt very fond of it. He said it was very dead, and some other things that were very blunt on not very nice about that design. And yeah I noticed the pretty texture. I appreciate that, but I think the current design is nice. the reason why all of the content is deisplayed on a white card background is the reason why the blue background is okay

However, I do agree we should increase the size of the link title on the card.

**Comment by julianpoy** [comment]
Alright. Its your project :)

**Comment by torch2424** [comment]
Dopeness :) <3 but yes Anything else, besides design/color changes you would like? readability wise?

**Comment by julianpoy** [comment]
Nope, its pretty much just the color. I can barely read the text on the page when its a deep color. Might just be my dyslexia.

**Comment by torch2424** [comment]
@julianpoy that is true it might, but we also want it to be accessible. I'll do some research on accessibility. Maybe we can make the cards pop more, or cantrast the background. I will learn it

**Comment by julianpoy** [comment]
I noticed a few things. I played with it and tried to figure out why I couldn't see the links. I figured it out!!!
The links... are the same exact color as the background. So my dyslexia goes insane.
If I just change the link color to the red of the find button (#732918), I can suddenly read it a little bit better. The other thing that helps, is if the font is 16px and font weight is 500.
Altogether, I honestly think it looks even better with the dark red links :D

**Comment by torch2424** [comment]
Yeah dude I'm down for that! Plus itll make things more interesting :)

**Comment by torch2424** [comment]
Are you already doing this? Or can I make a branch and apply these changes real quick?

**Comment by julianpoy** [comment]
I am not doing this

**Comment by torch2424** [comment]
I AM MUAHAHAHAHAHA

**Comment by torch2424** [comment]
Doing this in readability
