### ISSUE TITLE
Display some info like the title of a link

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-dump#3]
It would be nice to see the title of a link, would be very informative, and allow users to see what it is before clicking it

**Comment by torch2424** [comment]
This was completed as of f152cfe38fe42d5ec213805b1ba57007463ed274

**Comment by julianpoy** [comment]
(and this is why we branch and pull)

**Comment by torch2424** [comment]
@julianpoy Naw naw naw naw, this is a super personal project, it aint even close to going anywhere yet

**Comment by julianpoy** [comment]
@torch2424 I was just teeezing

**Comment by torch2424** [comment]
@julianpoy I know <3 ;)
