### ISSUE TITLE
Rename to Link Drops

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-dump#30]
We need to go through and remove all mentions of linkdump, and change it to link drops!

**Comment by torch2424** [comment]
Including file names and variable names for anyone who jumps onto the project!

**Comment by julianpoy** [comment]
I disagree with the idea of renaming internal things to link-drops. Project files and internal non-displayables should be kept to linkdump. It causes too much confusion and conflicts. This would cause ramifications in our database as well.

**Comment by torch2424** [comment]
Shiiiiii well alright I gues internal things will stick to dumps!

**Comment by torch2424** [comment]
Doing this now in reName
