### ISSUE TITLE
Add Support for Images

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-dump#31]
Images should be auto embedded, especially things like imgur and things

**Comment by julianpoy** [comment]
Before diving off the deep end with this, I believe we should discuss our methodology involving this. I think there might be an easier way for all of these specific items.

**Comment by julianpoy** [comment]
Also, duplicate of #9. This should be added to #9's list, and closed.

**Comment by julianpoy** [comment]
Closing this.
