### ISSUE TITLE
Get Titles Ourselves

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-dump#35]
Yes scraping walks a thin line. But it will save us alot of money from embedly!

Currently No Embed is our main title grabber, with embedly being the backup. we should be the backup just incase! and to keep costs low!

**Comment by torch2424** [comment]
We may also look into finding other providers to make embedly a third option!

**Comment by torch2424** [comment]
This is a good alternative for returning favicons

http://stackoverflow.com/questions/9856544/google-api-url-to-site-title

Or Julain suggested just going to the page before any slahes and  like Google.com/favicon.gif and simply use that

**Comment by torch2424** [comment]
Great for grabbing a pages title:

http://decenturl.com/tools

**Comment by julianpoy** [comment]
if you look at the reply on the link you posted (http://stackoverflow.com/questions/9856544/google-api-url-to-site-title), you will see that the very first reply (not answer) actually mentions my solution.

> Keep in mind that you can grab the favicon yourself by accessing it directly at www.whatevertheURLis.com/favicon.ico. I think the Google favicon tool was meant more for conversion. It outputs a png which can be used in img tags. –  ShiggityShiggityShwa

Seeing as we don't need conversion, there should be no reason not to grab it ourselves.

**Comment by julianpoy** [comment]
Ill handle this entire issue.

**Comment by torch2424** [comment]
@julianpoy Okay cool! you can handle the favicon. And I can handle the title? OR you wanna do all dat

**Comment by julianpoy** [comment]
I will handle all of it. I wrote a service to do the titles manually.
Try it out!
http://dev.kondeo.com/api/page-scraper.php?q=

**Comment by torch2424** [comment]
DUDE I FUKCING LOVE YOU!!!! :D
