### ISSUE TITLE
Webpages without defined title aren't clickable

### ISSUE THREAD

**Issue by julianpoy** [torch2424/link-dump#37]
To see what I mean, add http://test.com in your linkdump. As you can see, test.com has no title. There are several websites like this that have no title defined in their index.html. 
We should make the link title be the url in this case.

**Comment by torch2424** [comment]
Oh yeah forsure! Sounds good! I'll be sure to check for that!

**Comment by julianpoy** [comment]
This will be handled by my changes in #35
