### ISSUE TITLE
Update Frontend to work with the new RESTful Api

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-dump#39]
SInce things respond with statuses instead of error id and things. we need to update the front end to prepare itself for this!

**Comment by torch2424** [comment]
this issue was created to stay current with #38

**Comment by julianpoy** [comment]
As stated in #38, I did this as part of that very pull.

**Comment by torch2424** [comment]
@julianpoy When I tested, if I tried to make a duplicate user, I got the status code back, but the frontend was not ready for the status code, and gave no toast of the issue. Are you sure you adressed this?

**Comment by julianpoy** [comment]
I created #40 for this specific bug. All other routes have been updated. It seems I missed this one.

**Comment by torch2424** [comment]
Okay cool thank you!
