### ISSUE TITLE
Duplicate users not handled by frontend

### ISSUE THREAD

**Issue by julianpoy** [torch2424/link-dump#40]
In #38, RESTful status codes were implemented. The frontend has not been updated in the register section of the application.

**Comment by julianpoy** [comment]
This is not an issue. It was reported by @torch2424 as allowing users to sign up duplicates, however it does not. I have been able to duplicate what @torch2424 experienced, and it is because he was not using the backend on master via his local machine, and instead hooked up to the production server which does not use response codes yet.

**Comment by torch2424** [comment]
naw naw naw naw. I meant throught the frontend yo. THe backend wors great. I'm saying the frontend isnt catching these errors. the frontend need to catch these statueses to inform the user whats going on. And I did hook it up right to make sure I used the braackend branch and changed the apibase and all that jazz

**Comment by julianpoy** [comment]
The frontend captures the errors just fine using success/fail REST procedure. Please test this with the frontend pointed at the correct server.

**Comment by torch2424** [comment]
Maybe what I'm trying to say is the frontend is not handling it. like if we get Use not authorized, nothing toasts saying "USER not authorized".

You get what I'm saying? Maybe it is, and I'm derping? when I checked last night, I had to inspect element to figure out why I wasnt able to sign up

**Comment by julianpoy** [comment]
I understand now. Created #42
