### ISSUE TITLE
Allow Users to Suggest additional embed support, and leave suggestions

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-dump#48]
Maybe something in the footer. We gotta hear the people's voices! Allow them to request embed support for things, and leave suggestions to make the app better!

**Comment by torch2424** [comment]
Created an e-mail for this. suggestions@linkdrops.com

**Comment by julianpoy** [comment]
I suggest we use webmaster@linkdump.com. Google seo rankings hit higher if you have a webmaster email, and we might as well just have one to check.
