### ISSUE TITLE
Massive Memory Leak?

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-dump#56]
Link Drops seems to be using ALOT of memory, We should discover what is going on!

**Comment by julianpoy** [comment]
Could you investigate this with the chrome analyzer?

**Comment by torch2424** [comment]
sure yo!

**Comment by julianpoy** [comment]
How it do?

**Comment by torch2424** [comment]
To be honest, I dont quite understand how to use chrome's memory analyzer, but when I tried to figure out, it did seem like something was wrong. It was using ALOT of memory, but it wasnt the highest memory task actually. Honestly, I'd like it if we did this issue together. You're better at finding "wrong" code, than I am, and I think we could both use the learning experience

**Comment by julianpoy** [comment]
Coolio sounds like a plan

**Comment by torch2424** [comment]
After some research (Top 2 best):

http://www.codeproject.com/Articles/882966/Fixing-Memory-Leaks-in-AngularJS-and-other-JavaScr
http://makandracards.com/makandra/31289-how-to-create-giant-memory-leaks-in-angularjs
http://stackoverflow.com/questions/15970525/how-to-find-js-memory-leaks
http://addyosmani.com/blog/taming-the-unicorn-easing-javascript-memory-profiling-in-devtools/

I think I want to conclude that the application itseld is not leaking memory. I think it relates to the amount of iFrame the app uses. As I tested these methods on both the master linkdrops and aaronthedev (My simple personal site) and you can see they both react the same way. In linkdrops, I scrolled down, loaded all iframes, went to a page, and then went back did the same. And you will see that page switch, garbage collection happens, but does not return. I do the same on arronthedev, and i get the same results (Note in the end, i was letting the tab idle and do nothing, as you can see nothing is added to memory):

![untitled recording 3 1](https://cloud.githubusercontent.com/assets/1448289/10867420/4bbe4968-801e-11e5-96b9-dcb72f6862a8.gif)

I think what we need to do is instead, try to improve the performance of the app as a whole.

**Comment by torch2424** [comment]
Closing this, as I feel like I did a lot of testing and proven to a point that this issue is not a true issue, and I have gotten no feedback on this. So yeah, closing :)
