### ISSUE TITLE
Create a Chrome Extension

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-dump#83]
Create a chrome extension that will allow you to save the current tab, save and close, and save all tabs (maybe) :)

**Comment by julianpoy** [comment]
WOOOOT

**Comment by torch2424** [comment]
@julianpoy I sawy your comment in #84 , I want to do this while youre doing other issues, I want to complete the desktop experience before moving on to mobile :)

**Comment by torch2424** [comment]
I did in like 2 hours with like 2/3rds done. Need a bit of help of @julianpoy to get the backend down for this. Please see torch2424/link-drops-chrome-extension#1

**Comment by torch2424** [comment]
This has been completed
