### ISSUE TITLE
New layout blown up 50x

### ISSUE THREAD

**Issue by julianpoy** [torch2424/link-dump#86]
This is rediculous. The normal zoom level on link-drops new design looks like this.
https://www.dropbox.com/s/m137lqskmype85o/Screenshot%202015-11-15%2015.19.57.png?dl=0

Its harder to tell in the picture how rediculously big everything is. Its HUGE.
I mean
<h3>HUGE</h1>

**Comment by torch2424** [comment]
Oh yeah, like the text specifically? I can fix that :)

**Comment by julianpoy** [comment]
No, the entire interface. The cards are at least 1.5x larger than they used to be. Use the control key on your computer and zoom in to 175%, and thats what it looks like on every other computer in the world.
Your computer by default makes things tiny, so if it looks just about right to you, its extremely large for everyone else.

**Comment by torch2424** [comment]
I fixed it using three laptops right now :hamburger:

**Comment by julianpoy** [comment]
WOOOT

**Comment by julianpoy** [comment]
You da bestest <3

**Comment by torch2424** [comment]
@julianpoy Are you getting my texts/snaps? I wanted to ask you some stuff but I couldnt :'(

Also i tested onmy laptop, a chromebook, and a 15 inch macbook retina

**Comment by torch2424** [comment]
this was closed by #90
