### ISSUE TITLE
Angular Hints Unreasonable for some fields

### ISSUE THREAD

**Issue by julianpoy** [torch2424/link-dump#87]
I love the new angular hints/animations, but for some fields, like the tag field, its a little over the top. Theres some issues.

For instance, the angular hint pushes most everything way too high. The fields are extremely tall with the hint.
Example1:
https://www.dropbox.com/s/q6p7sfflo8mouh8/Screenshot%202015-11-15%2015.25.20.png?dl=0
Example2: 
https://www.dropbox.com/s/uoir61aheupkspm/Screenshot%202015-11-15%2015.26.38.png?dl=0
Example3:
https://www.dropbox.com/s/nhax3ku3drgyfsa/Screenshot%202015-11-15%2015.27.02.png?dl=0

**Comment by julianpoy** [comment]
(backburner tag not included)

**Comment by torch2424** [comment]
Oh damn the tags hahahaha :'D

**Comment by torch2424** [comment]
Do you mean like the placeholder text? And I think this is worth the sacrifice for the coolness of the field

**Comment by torch2424** [comment]
but also, I tried lowering the height, but it lowered it from the bottom not the top :'(
