### ISSUE TITLE
Delete image broken

### ISSUE THREAD

**Issue by julianpoy** [torch2424/link-dump#88]
For some reason, when the site was built last time, someone didnt do it correctly and broke a bunch of things. For instance:

https://www.dropbox.com/s/o83ifsjloua57f7/Screenshot%202015-11-15%2015.28.39.png?dl=0

**Comment by torch2424** [comment]
:'(

**Comment by torch2424** [comment]
Yo for some reason when i build the site, that image is missing, and the path ../views/linkcard.html int he grid directive is like 404'ing. And I cant figure out why grunt is missing those :/

**Comment by torch2424** [comment]
trying to fix this in publicBranch, Going to try this to fix templates: https://www.npmjs.com/package/grunt-angular-templates

**Comment by julianpoy** [comment]
Because they aren't added in a grunt pre-processing tag. You must add those types of paths in the correct place, so that grunt will minify and move them over.
